import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigration1775706620168 implements MigrationInterface {
    name = 'InitialMigration1775706620168'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('MEMBER', 'MANAGER', 'ADMIN')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "email" character varying NOT NULL, "password_hash" character varying NOT NULL, "full_name" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL DEFAULT 'MEMBER', "is_email_verified" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "is_suspended" boolean NOT NULL DEFAULT false, "is_banned" boolean NOT NULL DEFAULT false, "email_verification_token" text, "password_reset_token" text, "password_reset_expires_at" TIMESTAMP, "refresh_token" text, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_ace513fa30d485cfd25c11a9e4" ON "users" ("role") `);
        await queryRunner.query(`CREATE INDEX "IDX_70da251fe4ea495df8db457f8c" ON "users" ("is_active", "is_banned", "is_suspended") `);
        await queryRunner.query(`CREATE TYPE "public"."messes_currency_enum" AS ENUM('BDT', 'INR', 'USD', 'EUR', 'GBP')`);
        await queryRunner.query(`CREATE TYPE "public"."messes_status_enum" AS ENUM('PENDING_APPROVAL', 'ACTIVE', 'INACTIVE', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "messes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "name" character varying NOT NULL, "address" character varying NOT NULL, "description" text, "mess_id" text, "currency" "public"."messes_currency_enum" NOT NULL DEFAULT 'BDT', "status" "public"."messes_status_enum" NOT NULL DEFAULT 'PENDING_APPROVAL', "manager_id" uuid NOT NULL, "resubmission_count" integer NOT NULL DEFAULT '0', "rejection_notes" text, "requires_join_approval" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_6f09d69d70bf95762fd635979cf" UNIQUE ("mess_id"), CONSTRAINT "PK_043828fe17897e73eda8af683c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6f09d69d70bf95762fd635979c" ON "messes" ("mess_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f461d25de9f98cee95df5571d3" ON "messes" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_de00a9f840d292b10b041be53f" ON "messes" ("manager_id") `);
        await queryRunner.query(`CREATE TYPE "public"."mess_members_member_role_enum" AS ENUM('MEMBER', 'CO_MANAGER')`);
        await queryRunner.query(`CREATE TABLE "mess_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "mess_id" uuid NOT NULL, "user_id" uuid NOT NULL, "member_role" "public"."mess_members_member_role_enum" NOT NULL DEFAULT 'MEMBER', "join_date" date NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "is_guest" boolean NOT NULL DEFAULT false, "guest_valid_until" date, "participates_in_meals" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_b406dd162da9ec3e293f119032a" UNIQUE ("mess_id", "user_id"), CONSTRAINT "PK_0b0614ed1a1dfc4560e8be7146b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_96b85995809cfdf3840a9673ce" ON "mess_members" ("mess_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_560a9fc0a6036428126ec051bf" ON "mess_members" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b547e52f6285d09191ece0b156" ON "mess_members" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_78b82b9b169c3e1d2f68e7ce45" ON "mess_members" ("is_guest") `);
        await queryRunner.query(`CREATE TYPE "public"."shared_bill_invoices_payment_status_enum" AS ENUM('UNPAID', 'PAID')`);
        await queryRunner.query(`CREATE TYPE "public"."shared_bill_invoices_status_enum" AS ENUM('DRAFT', 'FINALIZED')`);
        await queryRunner.query(`CREATE TABLE "shared_bill_invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "mess_id" uuid NOT NULL, "mess_member_id" uuid NOT NULL, "month" integer NOT NULL, "year" integer NOT NULL, "total_share" numeric(10,2) NOT NULL, "active_member_count" integer NOT NULL, "payment_status" "public"."shared_bill_invoices_payment_status_enum" NOT NULL DEFAULT 'UNPAID', "pdf_url" text, "status" "public"."shared_bill_invoices_status_enum" NOT NULL DEFAULT 'DRAFT', CONSTRAINT "PK_e88f472c1f3651ee229cb70ba55" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_32ba07b33b8473227c1d1cc2a4" ON "shared_bill_invoices" ("mess_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9bcdad089627214f61fdb3972a" ON "shared_bill_invoices" ("mess_member_id") `);
        await queryRunner.query(`CREATE TYPE "public"."shared_bill_payments_method_enum" AS ENUM('CASH', 'BKASH', 'BANK_TRANSFER', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "shared_bill_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "shared_bill_invoice_id" uuid NOT NULL, "amount" numeric(10,2) NOT NULL, "method" "public"."shared_bill_payments_method_enum" NOT NULL, "payment_date" date NOT NULL, "reference_note" text, "recorded_by_id" uuid NOT NULL, CONSTRAINT "PK_df60102326bca2d1fd28dc130c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b5e26a50d933faa7f5f9607f2f" ON "shared_bill_payments" ("shared_bill_invoice_id") `);
        await queryRunner.query(`CREATE TABLE "shared_bill_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "mess_id" uuid NOT NULL, "name" character varying NOT NULL, "description" text, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_b48f3af385e64974cad29c79945" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7ff5fb3d573c656ba11a29c70f" ON "shared_bill_categories" ("mess_id") `);
        await queryRunner.query(`CREATE TABLE "shared_bill_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "category_id" uuid NOT NULL, "mess_id" uuid NOT NULL, "month" integer NOT NULL, "year" integer NOT NULL, "total_amount" numeric(10,2) NOT NULL, "reference_note" text, "entry_date" date NOT NULL, CONSTRAINT "UQ_c313ca4a25ef81f2c26e11b56da" UNIQUE ("category_id", "month", "year"), CONSTRAINT "PK_af32081213f2917eb7863cac480" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_755b111b79d166ee9b66f0341c" ON "shared_bill_entries" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0faaa2bf7221a1a06854e292c5" ON "shared_bill_entries" ("mess_id") `);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "user_id" uuid NOT NULL, "type" character varying NOT NULL, "title" character varying NOT NULL, "body" text NOT NULL, "data" jsonb, "is_read" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9a8a82462cab47c73d25f49261" ON "notifications" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_aef1c7aef3725068e5540f8f00" ON "notifications" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_f12148ce379462ebbb4d06cc13" ON "notifications" ("is_read") `);
        await queryRunner.query(`CREATE TYPE "public"."monthly_bill_summaries_status_enum" AS ENUM('OPEN', 'FINALIZED')`);
        await queryRunner.query(`CREATE TABLE "monthly_bill_summaries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "mess_id" uuid NOT NULL, "month" integer NOT NULL, "year" integer NOT NULL, "total_cost" numeric(12,2) NOT NULL DEFAULT '0', "total_portions" integer NOT NULL DEFAULT '0', "cost_per_meal" numeric(10,4) NOT NULL DEFAULT '0', "status" "public"."monthly_bill_summaries_status_enum" NOT NULL DEFAULT 'OPEN', "finalized_at" TIMESTAMP, CONSTRAINT "UQ_fd4e6cb4e1a9068b9ed19a39ff5" UNIQUE ("mess_id", "month", "year"), CONSTRAINT "PK_7803cb16e62f4f744bd30377386" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fe1944d8349b57c997c047ec37" ON "monthly_bill_summaries" ("mess_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7d5841c1c0408a17ebe0312e1f" ON "monthly_bill_summaries" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."meal_invoices_payment_status_enum" AS ENUM('UNPAID', 'PAID')`);
        await queryRunner.query(`CREATE TABLE "meal_invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "monthly_summary_id" uuid NOT NULL, "mess_member_id" uuid NOT NULL, "meal_portions" integer NOT NULL, "meal_subtotal" numeric(10,2) NOT NULL, "items_subtotal" numeric(10,2) NOT NULL, "fixed_charges_subtotal" numeric(10,2) NOT NULL, "total_amount" numeric(10,2) NOT NULL, "payment_status" "public"."meal_invoices_payment_status_enum" NOT NULL DEFAULT 'UNPAID', "pdf_url" text, CONSTRAINT "PK_2330bf3e3ec5389f8db2f66c1e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f14de7e0fbd55e10107f59e74b" ON "meal_invoices" ("monthly_summary_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e6a0514294f408628aca8b54de" ON "meal_invoices" ("mess_member_id") `);
        await queryRunner.query(`CREATE TYPE "public"."meal_payments_method_enum" AS ENUM('CASH', 'BKASH', 'BANK_TRANSFER', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "meal_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "meal_invoice_id" uuid NOT NULL, "amount" numeric(10,2) NOT NULL, "method" "public"."meal_payments_method_enum" NOT NULL, "payment_date" date NOT NULL, "reference_note" text, "recorded_by_id" uuid NOT NULL, CONSTRAINT "PK_7074c085c7f1a7fcb640c6e2cf0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c6ce894d0efe49dd4b060979d5" ON "meal_payments" ("meal_invoice_id") `);
        await queryRunner.query(`CREATE TYPE "public"."mess_deletion_requests_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "mess_deletion_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "mess_id" uuid NOT NULL, "manager_id" uuid NOT NULL, "reason" text NOT NULL, "status" "public"."mess_deletion_requests_status_enum" NOT NULL DEFAULT 'PENDING', "admin_notes" text, "processed_at" TIMESTAMP, CONSTRAINT "PK_e7aec6da44a51768c47e29b2865" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_eb585af995cde77e85bc0aec9c" ON "mess_deletion_requests" ("mess_id") `);
        await queryRunner.query(`CREATE TYPE "public"."meal_slots_type_enum" AS ENUM('BREAKFAST', 'LUNCH', 'DINNER')`);
        await queryRunner.query(`CREATE TYPE "public"."meal_slots_status_enum" AS ENUM('DRAFT', 'PUBLISHED')`);
        await queryRunner.query(`CREATE TABLE "meal_slots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "mess_id" uuid NOT NULL, "date" date NOT NULL, "type" "public"."meal_slots_type_enum" NOT NULL, "time_window_start" TIME NOT NULL, "time_window_end" TIME NOT NULL, "status" "public"."meal_slots_status_enum" NOT NULL DEFAULT 'DRAFT', "menu_description" text, "published_at" TIMESTAMP, CONSTRAINT "UQ_efffefc212e2a65d34404e1c021" UNIQUE ("mess_id", "date", "type"), CONSTRAINT "PK_615404ec302d601c28e8e47211f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dde5fdd945913470340a57dab1" ON "meal_slots" ("mess_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17fafa0e8c3fff7e83203cd58f" ON "meal_slots" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_1f5ca490fbbef72eeab61607d7" ON "meal_slots" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_6e7298d660a3021e94646395b6" ON "meal_slots" ("mess_id", "date") `);
        await queryRunner.query(`CREATE TYPE "public"."join_requests_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED')`);
        await queryRunner.query(`CREATE TABLE "join_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "mess_id" uuid NOT NULL, "user_id" uuid NOT NULL, "status" "public"."join_requests_status_enum" NOT NULL DEFAULT 'PENDING', "expires_at" TIMESTAMP NOT NULL, "processed_at" TIMESTAMP, CONSTRAINT "PK_3584a09620923a5aaf7de782f0d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bc2d1d083ae5c91d5ab6307092" ON "join_requests" ("mess_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b3ed52f33226ac678d4f931943" ON "join_requests" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a07dacd2f44436ff5a139042ca" ON "join_requests" ("expires_at") `);
        await queryRunner.query(`CREATE TABLE "item_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "mess_id" uuid NOT NULL, "name" character varying NOT NULL, "unit" character varying NOT NULL, "default_daily_quantity" numeric(10,3) NOT NULL, "cost_per_unit" numeric(10,2) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_3600946a4e5a3a75d973b016132" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_568627d0376b1190ff1e43b92b" ON "item_types" ("mess_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c4c90e47804d6d30eafc5477b2" ON "item_types" ("is_active") `);
        await queryRunner.query(`CREATE TYPE "public"."item_allocations_status_enum" AS ENUM('ALLOCATED', 'CANCELLED', 'ADJUSTED')`);
        await queryRunner.query(`CREATE TABLE "item_allocations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "item_type_id" uuid NOT NULL, "mess_member_id" uuid NOT NULL, "date" date NOT NULL, "quantity" numeric(10,3) NOT NULL, "status" "public"."item_allocations_status_enum" NOT NULL DEFAULT 'ALLOCATED', "cancelled_at" TIMESTAMP, CONSTRAINT "PK_e12e41643d4e85879e9f0db03cf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_883837a1218964f03a71348638" ON "item_allocations" ("item_type_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_61dafd43763a72091bd391d201" ON "item_allocations" ("mess_member_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1412c279992f4826df5bf244e4" ON "item_allocations" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_72d6e9be17a67fef97c4ec4ef0" ON "item_allocations" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_2d81559fbbef7759a410de6885" ON "item_allocations" ("mess_member_id", "date") `);
        await queryRunner.query(`CREATE TABLE "fixed_charges" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "mess_id" uuid NOT NULL, "name" character varying NOT NULL, "amount" numeric(10,2) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_04c6c1cd2fe5bb2363d8d6fa456" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8afaadd3b28fbfabd5141962a2" ON "fixed_charges" ("mess_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8b70689c8724084978a6ce7483" ON "fixed_charges" ("is_active") `);
        await queryRunner.query(`CREATE TYPE "public"."feedbacks_status_enum" AS ENUM('OPEN', 'RESOLVED')`);
        await queryRunner.query(`CREATE TABLE "feedbacks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "mess_member_id" uuid NOT NULL, "meal_slot_id" uuid, "date" date NOT NULL, "complaint" text NOT NULL, "status" "public"."feedbacks_status_enum" NOT NULL DEFAULT 'OPEN', "resolution_notes" text, "resolved_at" TIMESTAMP, CONSTRAINT "PK_79affc530fdd838a9f1e0cc30be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2430bc3b691d256816c9828d56" ON "feedbacks" ("mess_member_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3fca13bd922c6d2c1249068954" ON "feedbacks" ("meal_slot_id") `);
        await queryRunner.query(`CREATE TYPE "public"."daily_costs_category_enum" AS ENUM('INGREDIENT', 'UTILITY', 'LABOR', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "daily_costs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "mess_id" uuid NOT NULL, "date" date NOT NULL, "description" character varying NOT NULL, "quantity" numeric(10,3), "unit" text, "amount" numeric(10,2) NOT NULL, "category" "public"."daily_costs_category_enum" NOT NULL DEFAULT 'INGREDIENT', CONSTRAINT "PK_9a33a1cb9064d20f07662c3ba31" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_73d9a9b9db3526ea6a2dffce30" ON "daily_costs" ("mess_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_025e2d878a82838234ac6e4cad" ON "daily_costs" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_f6e012294679a2ca38f86e85b1" ON "daily_costs" ("mess_id", "date") `);
        await queryRunner.query(`CREATE TYPE "public"."bookings_status_enum" AS ENUM('BOOKED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "bookings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "meal_slot_id" uuid NOT NULL, "mess_member_id" uuid NOT NULL, "portions" integer NOT NULL DEFAULT '1', "status" "public"."bookings_status_enum" NOT NULL DEFAULT 'BOOKED', "cancelled_at" TIMESTAMP, CONSTRAINT "UQ_3401ae838f1bbb5a74d853aafd7" UNIQUE ("meal_slot_id", "mess_member_id"), CONSTRAINT "PK_bee6805982cc1e248e94ce94957" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ca4880d76f162ebe944c3a70fd" ON "bookings" ("meal_slot_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6e9c0554191d757f33a65c3bd0" ON "bookings" ("mess_member_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_48b267d894e32a25ebde4b207a" ON "bookings" ("status") `);
        await queryRunner.query(`ALTER TABLE "messes" ADD CONSTRAINT "FK_de00a9f840d292b10b041be53fa" FOREIGN KEY ("manager_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mess_members" ADD CONSTRAINT "FK_96b85995809cfdf3840a9673ce1" FOREIGN KEY ("mess_id") REFERENCES "messes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mess_members" ADD CONSTRAINT "FK_560a9fc0a6036428126ec051bf4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shared_bill_invoices" ADD CONSTRAINT "FK_32ba07b33b8473227c1d1cc2a4a" FOREIGN KEY ("mess_id") REFERENCES "messes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shared_bill_invoices" ADD CONSTRAINT "FK_9bcdad089627214f61fdb3972a2" FOREIGN KEY ("mess_member_id") REFERENCES "mess_members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shared_bill_payments" ADD CONSTRAINT "FK_b5e26a50d933faa7f5f9607f2fd" FOREIGN KEY ("shared_bill_invoice_id") REFERENCES "shared_bill_invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shared_bill_payments" ADD CONSTRAINT "FK_b20a719b4501fa7af08baaf15c7" FOREIGN KEY ("recorded_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shared_bill_categories" ADD CONSTRAINT "FK_7ff5fb3d573c656ba11a29c70fe" FOREIGN KEY ("mess_id") REFERENCES "messes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shared_bill_entries" ADD CONSTRAINT "FK_755b111b79d166ee9b66f0341ce" FOREIGN KEY ("category_id") REFERENCES "shared_bill_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shared_bill_entries" ADD CONSTRAINT "FK_0faaa2bf7221a1a06854e292c55" FOREIGN KEY ("mess_id") REFERENCES "messes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "monthly_bill_summaries" ADD CONSTRAINT "FK_fe1944d8349b57c997c047ec37f" FOREIGN KEY ("mess_id") REFERENCES "messes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meal_invoices" ADD CONSTRAINT "FK_f14de7e0fbd55e10107f59e74bf" FOREIGN KEY ("monthly_summary_id") REFERENCES "monthly_bill_summaries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meal_invoices" ADD CONSTRAINT "FK_e6a0514294f408628aca8b54de1" FOREIGN KEY ("mess_member_id") REFERENCES "mess_members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meal_payments" ADD CONSTRAINT "FK_c6ce894d0efe49dd4b060979d57" FOREIGN KEY ("meal_invoice_id") REFERENCES "meal_invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meal_payments" ADD CONSTRAINT "FK_391eed734f3ef4e4d80cc554f6d" FOREIGN KEY ("recorded_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mess_deletion_requests" ADD CONSTRAINT "FK_eb585af995cde77e85bc0aec9c4" FOREIGN KEY ("mess_id") REFERENCES "messes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mess_deletion_requests" ADD CONSTRAINT "FK_4145403b143ed864af3a00d73cb" FOREIGN KEY ("manager_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meal_slots" ADD CONSTRAINT "FK_dde5fdd945913470340a57dab16" FOREIGN KEY ("mess_id") REFERENCES "messes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "join_requests" ADD CONSTRAINT "FK_bc2d1d083ae5c91d5ab63070923" FOREIGN KEY ("mess_id") REFERENCES "messes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "join_requests" ADD CONSTRAINT "FK_b3ed52f33226ac678d4f931943a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item_types" ADD CONSTRAINT "FK_568627d0376b1190ff1e43b92b6" FOREIGN KEY ("mess_id") REFERENCES "messes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item_allocations" ADD CONSTRAINT "FK_883837a1218964f03a713486383" FOREIGN KEY ("item_type_id") REFERENCES "item_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item_allocations" ADD CONSTRAINT "FK_61dafd43763a72091bd391d2019" FOREIGN KEY ("mess_member_id") REFERENCES "mess_members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fixed_charges" ADD CONSTRAINT "FK_8afaadd3b28fbfabd5141962a22" FOREIGN KEY ("mess_id") REFERENCES "messes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feedbacks" ADD CONSTRAINT "FK_2430bc3b691d256816c9828d567" FOREIGN KEY ("mess_member_id") REFERENCES "mess_members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feedbacks" ADD CONSTRAINT "FK_3fca13bd922c6d2c1249068954b" FOREIGN KEY ("meal_slot_id") REFERENCES "meal_slots"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "daily_costs" ADD CONSTRAINT "FK_73d9a9b9db3526ea6a2dffce300" FOREIGN KEY ("mess_id") REFERENCES "messes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_ca4880d76f162ebe944c3a70fdc" FOREIGN KEY ("meal_slot_id") REFERENCES "meal_slots"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_6e9c0554191d757f33a65c3bd0a" FOREIGN KEY ("mess_member_id") REFERENCES "mess_members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_6e9c0554191d757f33a65c3bd0a"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_ca4880d76f162ebe944c3a70fdc"`);
        await queryRunner.query(`ALTER TABLE "daily_costs" DROP CONSTRAINT "FK_73d9a9b9db3526ea6a2dffce300"`);
        await queryRunner.query(`ALTER TABLE "feedbacks" DROP CONSTRAINT "FK_3fca13bd922c6d2c1249068954b"`);
        await queryRunner.query(`ALTER TABLE "feedbacks" DROP CONSTRAINT "FK_2430bc3b691d256816c9828d567"`);
        await queryRunner.query(`ALTER TABLE "fixed_charges" DROP CONSTRAINT "FK_8afaadd3b28fbfabd5141962a22"`);
        await queryRunner.query(`ALTER TABLE "item_allocations" DROP CONSTRAINT "FK_61dafd43763a72091bd391d2019"`);
        await queryRunner.query(`ALTER TABLE "item_allocations" DROP CONSTRAINT "FK_883837a1218964f03a713486383"`);
        await queryRunner.query(`ALTER TABLE "item_types" DROP CONSTRAINT "FK_568627d0376b1190ff1e43b92b6"`);
        await queryRunner.query(`ALTER TABLE "join_requests" DROP CONSTRAINT "FK_b3ed52f33226ac678d4f931943a"`);
        await queryRunner.query(`ALTER TABLE "join_requests" DROP CONSTRAINT "FK_bc2d1d083ae5c91d5ab63070923"`);
        await queryRunner.query(`ALTER TABLE "meal_slots" DROP CONSTRAINT "FK_dde5fdd945913470340a57dab16"`);
        await queryRunner.query(`ALTER TABLE "mess_deletion_requests" DROP CONSTRAINT "FK_4145403b143ed864af3a00d73cb"`);
        await queryRunner.query(`ALTER TABLE "mess_deletion_requests" DROP CONSTRAINT "FK_eb585af995cde77e85bc0aec9c4"`);
        await queryRunner.query(`ALTER TABLE "meal_payments" DROP CONSTRAINT "FK_391eed734f3ef4e4d80cc554f6d"`);
        await queryRunner.query(`ALTER TABLE "meal_payments" DROP CONSTRAINT "FK_c6ce894d0efe49dd4b060979d57"`);
        await queryRunner.query(`ALTER TABLE "meal_invoices" DROP CONSTRAINT "FK_e6a0514294f408628aca8b54de1"`);
        await queryRunner.query(`ALTER TABLE "meal_invoices" DROP CONSTRAINT "FK_f14de7e0fbd55e10107f59e74bf"`);
        await queryRunner.query(`ALTER TABLE "monthly_bill_summaries" DROP CONSTRAINT "FK_fe1944d8349b57c997c047ec37f"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "shared_bill_entries" DROP CONSTRAINT "FK_0faaa2bf7221a1a06854e292c55"`);
        await queryRunner.query(`ALTER TABLE "shared_bill_entries" DROP CONSTRAINT "FK_755b111b79d166ee9b66f0341ce"`);
        await queryRunner.query(`ALTER TABLE "shared_bill_categories" DROP CONSTRAINT "FK_7ff5fb3d573c656ba11a29c70fe"`);
        await queryRunner.query(`ALTER TABLE "shared_bill_payments" DROP CONSTRAINT "FK_b20a719b4501fa7af08baaf15c7"`);
        await queryRunner.query(`ALTER TABLE "shared_bill_payments" DROP CONSTRAINT "FK_b5e26a50d933faa7f5f9607f2fd"`);
        await queryRunner.query(`ALTER TABLE "shared_bill_invoices" DROP CONSTRAINT "FK_9bcdad089627214f61fdb3972a2"`);
        await queryRunner.query(`ALTER TABLE "shared_bill_invoices" DROP CONSTRAINT "FK_32ba07b33b8473227c1d1cc2a4a"`);
        await queryRunner.query(`ALTER TABLE "mess_members" DROP CONSTRAINT "FK_560a9fc0a6036428126ec051bf4"`);
        await queryRunner.query(`ALTER TABLE "mess_members" DROP CONSTRAINT "FK_96b85995809cfdf3840a9673ce1"`);
        await queryRunner.query(`ALTER TABLE "messes" DROP CONSTRAINT "FK_de00a9f840d292b10b041be53fa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_48b267d894e32a25ebde4b207a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e9c0554191d757f33a65c3bd0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ca4880d76f162ebe944c3a70fd"`);
        await queryRunner.query(`DROP TABLE "bookings"`);
        await queryRunner.query(`DROP TYPE "public"."bookings_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f6e012294679a2ca38f86e85b1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_025e2d878a82838234ac6e4cad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_73d9a9b9db3526ea6a2dffce30"`);
        await queryRunner.query(`DROP TABLE "daily_costs"`);
        await queryRunner.query(`DROP TYPE "public"."daily_costs_category_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3fca13bd922c6d2c1249068954"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2430bc3b691d256816c9828d56"`);
        await queryRunner.query(`DROP TABLE "feedbacks"`);
        await queryRunner.query(`DROP TYPE "public"."feedbacks_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b70689c8724084978a6ce7483"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8afaadd3b28fbfabd5141962a2"`);
        await queryRunner.query(`DROP TABLE "fixed_charges"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2d81559fbbef7759a410de6885"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_72d6e9be17a67fef97c4ec4ef0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1412c279992f4826df5bf244e4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_61dafd43763a72091bd391d201"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_883837a1218964f03a71348638"`);
        await queryRunner.query(`DROP TABLE "item_allocations"`);
        await queryRunner.query(`DROP TYPE "public"."item_allocations_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c4c90e47804d6d30eafc5477b2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_568627d0376b1190ff1e43b92b"`);
        await queryRunner.query(`DROP TABLE "item_types"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a07dacd2f44436ff5a139042ca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b3ed52f33226ac678d4f931943"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bc2d1d083ae5c91d5ab6307092"`);
        await queryRunner.query(`DROP TABLE "join_requests"`);
        await queryRunner.query(`DROP TYPE "public"."join_requests_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e7298d660a3021e94646395b6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1f5ca490fbbef72eeab61607d7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17fafa0e8c3fff7e83203cd58f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dde5fdd945913470340a57dab1"`);
        await queryRunner.query(`DROP TABLE "meal_slots"`);
        await queryRunner.query(`DROP TYPE "public"."meal_slots_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."meal_slots_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eb585af995cde77e85bc0aec9c"`);
        await queryRunner.query(`DROP TABLE "mess_deletion_requests"`);
        await queryRunner.query(`DROP TYPE "public"."mess_deletion_requests_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c6ce894d0efe49dd4b060979d5"`);
        await queryRunner.query(`DROP TABLE "meal_payments"`);
        await queryRunner.query(`DROP TYPE "public"."meal_payments_method_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e6a0514294f408628aca8b54de"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f14de7e0fbd55e10107f59e74b"`);
        await queryRunner.query(`DROP TABLE "meal_invoices"`);
        await queryRunner.query(`DROP TYPE "public"."meal_invoices_payment_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d5841c1c0408a17ebe0312e1f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe1944d8349b57c997c047ec37"`);
        await queryRunner.query(`DROP TABLE "monthly_bill_summaries"`);
        await queryRunner.query(`DROP TYPE "public"."monthly_bill_summaries_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f12148ce379462ebbb4d06cc13"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aef1c7aef3725068e5540f8f00"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a8a82462cab47c73d25f49261"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0faaa2bf7221a1a06854e292c5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_755b111b79d166ee9b66f0341c"`);
        await queryRunner.query(`DROP TABLE "shared_bill_entries"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7ff5fb3d573c656ba11a29c70f"`);
        await queryRunner.query(`DROP TABLE "shared_bill_categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b5e26a50d933faa7f5f9607f2f"`);
        await queryRunner.query(`DROP TABLE "shared_bill_payments"`);
        await queryRunner.query(`DROP TYPE "public"."shared_bill_payments_method_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9bcdad089627214f61fdb3972a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32ba07b33b8473227c1d1cc2a4"`);
        await queryRunner.query(`DROP TABLE "shared_bill_invoices"`);
        await queryRunner.query(`DROP TYPE "public"."shared_bill_invoices_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."shared_bill_invoices_payment_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78b82b9b169c3e1d2f68e7ce45"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b547e52f6285d09191ece0b156"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_560a9fc0a6036428126ec051bf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_96b85995809cfdf3840a9673ce"`);
        await queryRunner.query(`DROP TABLE "mess_members"`);
        await queryRunner.query(`DROP TYPE "public"."mess_members_member_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_de00a9f840d292b10b041be53f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f461d25de9f98cee95df5571d3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6f09d69d70bf95762fd635979c"`);
        await queryRunner.query(`DROP TABLE "messes"`);
        await queryRunner.query(`DROP TYPE "public"."messes_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."messes_currency_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_70da251fe4ea495df8db457f8c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ace513fa30d485cfd25c11a9e4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
    }

}
